### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Pererozhdennyy** [Koziev/ruword2tags#1]
![image](https://user-images.githubusercontent.com/62129215/166155314-fe5304c4-b38e-480d-82d2-0f36f9df0f4c.png)

**Comment by Koziev** [comment]
Привет,

к сожалению, файл со словарем ruword2tags.dat слишком большой и выходит за лимиты гитхаба, поэтому я не могу его разместить вместе с самим пакетом :(

Его можно сказать отсюда https://drive.google.com/file/d/12nZbAuyiEH2v0X9Y5ZS0-u0y3TMVPX7w/view?usp=sharing и просто поместить в папку с пакетом ruword2tags.

**Comment by Pererozhdennyy** [comment]
> rename .db to .dat?

**Comment by Koziev** [comment]
Упс, я неверно прочинат соощение об ошибке :(

Вот ссылка на скачивание файла ruword2tags.dat: https://drive.google.com/file/d/1dPRpoKX4DqcNON8x76DQFdsBpehnyu2r/view?usp=sharing

Впрочем, файл ruword2tags.db тоже будет нужен - он доступен по предыдущей ссылке.
